// =====================================================
//
// This file was generated by LinearMPC.jl
// If you find it useful, consider citing the paper:
//
//     "A Dual Active-Set Solver for Embedded Quadratic Programming Using Recursive LDL Updates" 
//     Arnström, D. and Bemporad, A. and Axehill, D.
//     IEEE Transactions on Automatic Control
//
// Also, any feedback or success stories from using LinearMPC.jl and/or DAQP
// is gladly recieved at daniel.arnstrom@gmail.com
//
// =====================================================
